version: "3.9"

services:
   api:
      build:
         context: .
         dockerfile: Dockerfile.dev
      command: python3 manage.py runserver 0.0.0.0:8000
      # volume here mounts the code to the container and updates
      # the container whenever a change to source code is made
      # without this you would have to rebuild each time changes are made to source code. ONLY to be used in DEVELOPMENT
      volumes:
         - .:/app
      # ports:
      #    - 8000:8000
      env_file:
         - .env
      restart: "on-failure"
      depends_on:
         - postgres-db
      networks:
         - hospital-api

   postgres-db:
      # we use an image that has PostgreSQL and PostGIS which is
      # a spatial database extender for PostgreSQL
      image: kartoza/postgis:12.0
      ports:
         - 5432:5432
      #volume for persistent storage
      volumes:
         - postgres_data:/var/lib/postgresql
      environment:
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASS=${POSTGRES_PASS}
         - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      restart: "on-failure"
      networks:
         - hospital-api

   nginx:
      restart: always
      depends_on:
         - api
      build:
         context: ./nginx
         dockerfile: Dockerfile.dev
      ports:
         - 8080:80
      networks:
         - hospital-api

networks:
   hospital-api:
      driver: bridge

volumes:
   postgres_data:
