# Generated by Django 3.1.7 on 2021-03-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_distance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='distance',
            new_name='distance1',
        ),
    ]
