# Generated by Django 3.1.7 on 2021-03-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20210328_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='distance1',
        ),
    ]
