# Generated by Django 3.1.7 on 2021-03-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_remove_hospital_distance1'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='distance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distance'),
        ),
    ]
