# Generated by Django 3.1.7 on 2021-03-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_hospital_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='distance',
        ),
    ]
