# Generated by Django 3.1.7 on 2021-04-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_remove_hospital_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='beds',
            field=models.IntegerField(default=1, verbose_name='Bed Numbers'),
        ),
    ]
