# Generated by Django 3.1.7 on 2021-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='adm1_pcode',
            field=models.CharField(max_length=254, verbose_name='Border Code'),
        ),
    ]
