# Generated by Django 3.1.7 on 2021-04-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0002_auto_20210328_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boundary',
            name='adm1_pcode',
            field=models.CharField(max_length=254, verbose_name='Boundary Code'),
        ),
        migrations.AlterField(
            model_name='boundary',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Boundary Name'),
        ),
    ]
